mayikt:
  name: 刘宇星
  age: 18
#luo:
#  name: luoyaozhong
#  age: 20
spring:
  profiles:
    active: prd
server:
  port: 8081
  servlet:
#    设置springboot访问路径
    context-path: /mayikt
logging:
  config: classpath:log4j.properties